<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect([
            [
                'name' => 'Dashboard',
                'main_menu_id' => 1,
                'slug' => 'dashboard',
                'display' => 1,
                'url' => '/',
                'icon' => 'bi bi-speedometer2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bahan Mentah',
                'main_menu_id' => 2,
                'slug' => 'bahan-mentah',
                'display' => 1,
                'url' => '/raw-ingredients',
                'icon' => 'bi bi-cart4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tambah Bahan Mentah',
                'main_menu_id' => 2,
                'slug' => 'tambah-bahan-mentah',
                'display' => 0,
                'url' => '/raw-ingredients/add-new',
                'icon' => 'bi bi-plus-circle me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Bahan Mentah',
                'main_menu_id' => 2,
                'slug' => 'ubah-bahan-mentah',
                'display' => 0,
                'url' => '/raw-ingredients/{code}/edit',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mengaktifkan Bahan Mentah',
                'main_menu_id' => 2,
                'slug' => 'mengaktifkan-bahan-mentah',
                'display' => 0,
                'url' => '/raw-ingredients/{code}/activate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menonaktifkan Bahan Mentah',
                'main_menu_id' => 2,
                'slug' => 'menonaktifkan-bahan-mentah',
                'display' => 0,
                'url' => '/raw-ingredients/{code}/deactivate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menghapus Bahan Mentah',
                'main_menu_id' => 2,
                'slug' => 'menghapus-bahan-mentah',
                'display' => 0,
                'url' => '/raw-ingredients/{code}/delete',
                'icon' => 'bi bi-trash me-md-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bahan Dalam Proses',
                'main_menu_id' => 3,
                'slug' => 'bahan-dalam-proses',
                'display' => 1,
                'url' => '/on-process-ingredients',
                'icon' => 'bi bi-cpu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tambah Bahan Dalam Proses',
                'main_menu_id' => 3,
                'slug' => 'tambah-bahan-dalam-proses',
                'display' => 0,
                'url' => '/on-process-ingredients/add-new',
                'icon' => 'bi bi-plus-circle me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Bahan Dalam Proses',
                'main_menu_id' => 3,
                'slug' => 'ubah-bahan-dalam-proses',
                'display' => 0,
                'url' => '/on-process-ingredients/{code}/edit',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mengaktifkan Bahan Dalam Proses',
                'main_menu_id' => 3,
                'slug' => 'mengaktifkan-bahan-dalam-proses',
                'display' => 0,
                'url' => '/on-process-ingredients/{code}/activate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menonaktifkan Bahan Dalam Proses',
                'main_menu_id' => 3,
                'slug' => 'menonaktifkan-bahan-dalam-proses',
                'display' => 0,
                'url' => '/on-process-ingredients/{code}/deactivate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menghapus Bahan Dalam Proses',
                'main_menu_id' => 3,
                'slug' => 'menghapus-bahan-dalam-proses',
                'display' => 0,
                'url' => '/on-process-ingredients/{code}/delete',
                'icon' => 'bi bi-trash me-md-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Barang Jadi',
                'main_menu_id' => 4,
                'slug' => 'barang-jadi',
                'display' => 1,
                'url' => '/products',
                'icon' => 'bi bi-bag-check',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tambah Barang Jadi',
                'main_menu_id' => 4,
                'slug' => 'tambah-barang-jadi',
                'display' => 0,
                'url' => '/products/add-new',
                'icon' => 'bi bi-plus-circle me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Barang Jadi',
                'main_menu_id' => 4,
                'slug' => 'ubah-barang-jadi',
                'display' => 0,
                'url' => '/products/{code}/edit',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mengaktifkan Barang Jadi',
                'main_menu_id' => 4,
                'slug' => 'mengaktifkan-barang-jadi',
                'display' => 0,
                'url' => '/products/{code}/activate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menonaktifkan Barang Jadi',
                'main_menu_id' => 4,
                'slug' => 'menonaktifkan-barang-jadi',
                'display' => 0,
                'url' => '/products/{code}/deactivate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menghapus Barang Jadi',
                'main_menu_id' => 4,
                'slug' => 'menghapus-barang-jadi',
                'display' => 0,
                'url' => '/products/{code}/delete',
                'icon' => 'bi bi-trash me-md-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pemasukan',
                'main_menu_id' => 5,
                'slug' => 'pemasukan',
                'display' => 1,
                'url' => '/incomes',
                'icon' => 'bi bi-arrow-down-circle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tambah Pemasukan',
                'main_menu_id' => 5,
                'slug' => 'tambah-pemasukan',
                'display' => 0,
                'url' => '/incomes/add-new',
                'icon' => 'bi bi-plus-circle me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Pemasukan',
                'main_menu_id' => 5,
                'slug' => 'ubah-pemasukan',
                'display' => 0,
                'url' => '/incomes/{code}/edit',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mengaktifkan Pemasukan',
                'main_menu_id' => 5,
                'slug' => 'mengaktifkan-pemasukan',
                'display' => 0,
                'url' => '/incomes/{code}/activate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menonaktifkan Pemasukan',
                'main_menu_id' => 5,
                'slug' => 'menonaktifkan-pemasukan',
                'display' => 0,
                'url' => '/incomes/{code}/deactivate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menghapus Pemasukan',
                'main_menu_id' => 5,
                'slug' => 'menghapus-pemasukan',
                'display' => 0,
                'url' => '/incomes/{code}/delete',
                'icon' => 'bi bi-trash me-md-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pengeluaran',
                'main_menu_id' => 6,
                'slug' => 'pengeluaran',
                'display' => 1,
                'url' => '/expenses',
                'icon' => 'bi bi-arrow-up-circle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tambah Pengeluaran',
                'main_menu_id' => 6,
                'slug' => 'tambah-pengeluaran',
                'display' => 0,
                'url' => '/expenses/add-new',
                'icon' => 'bi bi-plus-circle me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Pengeluaran',
                'main_menu_id' => 6,
                'slug' => 'ubah-pengeluaran',
                'display' => 0,
                'url' => '/expenses/{code}/edit',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menghapus Pengeluaran',
                'main_menu_id' => 6,
                'slug' => 'menghapus-pengeluaran',
                'display' => 0,
                'url' => '/expenses/{code}/delete',
                'icon' => 'bi bi-trash me-md-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hutang',
                'main_menu_id' => 7,
                'slug' => 'hutang',
                'display' => 1,
                'url' => '/debts',
                'icon' => 'bi bi-emoji-dizzy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tambah Hutang',
                'main_menu_id' => 7,
                'slug' => 'tambah-hutang',
                'display' => 0,
                'url' => '/debts/add-new',
                'icon' => 'bi bi-plus-circle me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Hutang',
                'main_menu_id' => 7,
                'slug' => 'ubah-hutang',
                'display' => 0,
                'url' => '/debts/{code}/edit',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mengaktifkan Hutang',
                'main_menu_id' => 7,
                'slug' => 'mengaktifkan-hutang',
                'display' => 0,
                'url' => '/debts/{code}/activate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menonaktifkan Hutang',
                'main_menu_id' => 7,
                'slug' => 'menonaktifkan-hutang',
                'display' => 0,
                'url' => '/debts/{code}/deactivate',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menghapus Hutang',
                'main_menu_id' => 7,
                'slug' => 'menghapus-hutang',
                'display' => 0,
                'url' => '/debts/{code}/delete',
                'icon' => 'bi bi-trash me-md-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pengguna',
                'main_menu_id' => 8,
                'slug' => 'pengguna',
                'display' => 1,
                'url' => '/users',
                'icon' => 'bi bi-people',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Registrasi Pengguna',
                'main_menu_id' => 8,
                'slug' => 'registrasi-pengguna',
                'display' => 0,
                'url' => '/users/register',
                'icon' => 'bi bi-plus-circle me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Pengguna',
                'main_menu_id' => 8,
                'slug' => 'ubah-pengguna',
                'display' => 0,
                'url' => '/users/{username}/edit',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menghapus Pengguna',
                'main_menu_id' => 8,
                'slug' => 'menghapus-pengguna',
                'display' => 0,
                'url' => '/users/{username}/delete',
                'icon' => 'bi bi-trash me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mengaktifkan Pengguna',
                'main_menu_id' => 8,
                'slug' => 'mengaktifkan-pengguna',
                'display' => 0,
                'url' => '/users/activate/{username}',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menonaktifkan Pengguna',
                'main_menu_id' => 8,
                'slug' => 'menonaktifkan-pengguna',
                'display' => 0,
                'url' => '/users/deactivate/{username}',
                'icon' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pengaturan',
                'main_menu_id' => 9,
                'slug' => 'pengaturan',
                'display' => 1,
                'url' => '/settings',
                'icon' => 'bi bi-gear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Profil',
                'main_menu_id' => 9,
                'slug' => 'ubah-profil',
                'display' => 0,
                'url' => '/settings/user-profile/{username}',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Profil Perusahaan',
                'main_menu_id' => 9,
                'slug' => 'ubah-profil-perusahaan',
                'display' => 1,
                'url' => '/settings/company-profile',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Role',
                'main_menu_id' => 9,
                'slug' => 'role',
                'display' => 1,
                'url' => '/roles',
                'icon' => 'bi bi-people me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tambah Role',
                'main_menu_id' => 9,
                'slug' => 'tambah-role',
                'display' => 0,
                'url' => '/roles/add-new',
                'icon' => 'bi bi-plus-circle me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Role',
                'main_menu_id' => 9,
                'slug' => 'ubah-role',
                'display' => 0,
                'url' => '/roles/{name}/edit',
                'icon' => 'bi bi-pencil me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Menghapus Role',
                'main_menu_id' => 9,
                'slug' => 'menghapus-role',
                'display' => 0,
                'url' => '/roles/{name}/delete',
                'icon' => 'bi bi-trash me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubah Hak Akses',
                'main_menu_id' => 9,
                'slug' => 'ubah-hak-akses',
                'display' => 0,
                'url' => '/privileges/{name}/edit',
                'icon' => 'bi bi-people me-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ])->each(function($menu) {
            DB::table('menus')->insert($menu);
        });
    }
}
